using System.Windows;

namespace DenoVideoPlayer.Services;

public sealed class LocalizedText
{
    private readonly object?[] _arguments;

    public LocalizedText(string key, params object?[] arguments)
    {
        Key = key;
        _arguments = arguments.Length == 0
            ? Array.Empty<object?>()
            : arguments.ToArray();
    }

    public string Key { get; }

    public override string ToString() =>
        LocalizationService.F(Key, _arguments);
}

public sealed class LocalizedDetailException : Exception
{
    public LocalizedDetailException(LocalizedText detail)
        : base(detail.ToString())
    {
        Detail = detail;
    }

    public LocalizedText Detail { get; }
}

public static class LocalizationService
{
    public const string Korean = "ko";
    public const string English = "en";

    private static string _currentLanguage = Korean;
    public static string CurrentLanguage => _currentLanguage;

    public static event Action? LanguageChanged;

    public static void Apply(string? language)
    {
        var normalized = Normalize(language);
        _currentLanguage = normalized;

        if (Application.Current is { } app)
        {
            foreach (var (key, value) in StringsFor(normalized))
                app.Resources[key] = value;
        }

        LanguageChanged?.Invoke();
    }

    public static string Normalize(string? language)
        => string.Equals(language, English, StringComparison.OrdinalIgnoreCase)
            ? English
            : Korean;

    public static string T(string key)
    {
        var dict = StringsFor(_currentLanguage);
        if (dict.TryGetValue(key, out var value)) return value;
        return KoreanStrings.TryGetValue(key, out var fallback) ? fallback : key;
    }

    public static string F(string key, params object?[] args)
        => string.Format(T(key), args);

    private static IReadOnlyDictionary<string, string> StringsFor(string language)
        => language == English ? EnglishStrings : KoreanStrings;

    private static readonly Dictionary<string, string> KoreanStrings = new()
    {
        ["AppName"] = "Deno Video Player",
        ["TooltipRecent"] = "최근 파일 (Ctrl+H) · 왼쪽 중앙 손잡이",
        ["TooltipPlaylist"] = "재생목록 (P / Ctrl+L) · 오른쪽 중앙 손잡이",
        ["TooltipAlwaysOnTop"] = "항상 위 (Ctrl+T)",
        ["TooltipScreenshot"] = "스크린샷 (Ctrl+S)",
        ["TooltipTrimStart"] = "자르기 편집 시작",
        ["TooltipTrimExit"] = "자르기 편집 종료 (저장 안 함)",
        ["TooltipTrimCancel"] = "취소 — 편집 모드 종료",
        ["TooltipOpenFolder"] = "폴더 열기",
        ["TooltipOpenFile"] = "파일 열기 (Ctrl+O)",
        ["TooltipHelp"] = "사용 방법 및 단축키 (F1)",
        ["TooltipSettings"] = "환경설정 — 연결 프로그램 등록",
        ["TooltipMinimize"] = "최소화",
        ["TooltipMaxRestore"] = "전체화면 / 원래 창 크기 (F)",
        ["TooltipClose"] = "닫기",
        ["AudioPlaying"] = "오디오 재생 중",
        ["HeroBrand"] = "DENO VIDEO PLAYER",
        ["DropHeadline"] = "미디어를 끌어다 놓으세요",
        ["DropSubline"] = "또는 Ctrl+O / 아래 버튼으로 열기",
        ["OpenFile"] = "파일 열기",
        ["OpenFolder"] = "폴더 열기",
        ["HelpFirstUse"] = "처음이신가요? 빠른 사용법 보기 (F1)",
        ["SupportedFormats"] = ".mp4 .mkv .mov .webm  ·  .mp3 .flac .wav  ·  .png .jpg .gif",
        ["PlaybackFailed"] = "재생할 수 없습니다",
        ["PlaybackEngineFailed"] = "재생 엔진을 사용할 수 없습니다",
        ["OpenOtherFile"] = "다른 파일 열기",
        ["NextFile"] = "다음 파일",
        ["RetryPlaybackEngine"] = "재생 엔진 다시 시도",
        ["Troubleshooting"] = "문제 해결",
        ["Loading"] = "로딩 중",
        ["TrimInPoint"] = "IN 지점",
        ["TrimOutPoint"] = "OUT 지점",
        ["TooltipPrev"] = "이전 파일 (PageUp / Ctrl+←)",
        ["TooltipPlayPause"] = "재생/일시정지 (Space)",
        ["TooltipNext"] = "다음 파일 (PageDown / Ctrl+→)",
        ["TooltipRepeatNone"] = "반복 안 함 (전체 한 번 끝나면 멈춤)",
        ["TooltipRepeatAll"] = "전체 반복 (마지막 곡 끝나면 처음으로)",
        ["TooltipRepeatOne"] = "한 곡 반복 (현재 곡만 계속)",
        ["TooltipMute"] = "음소거 (M)",
        ["TooltipSpeed"] = "배속 — 클릭: 프리셋, 휠: ±0.25, Shift + . / Shift + ,",
        ["SpeedDefault"] = "1.0x — 기본",
        ["TooltipFullscreen"] = "전체화면 / 원래 창 크기 (F)",
        ["TooltipImmersiveFullscreen"] = "컨트롤 숨기기 (화면 크기 유지)",
        ["TrimEditingPrefix"] = "편집 중 — ",
        ["TrimEditingSuffix"] = "  ·  양쪽 핸들 드래그로 IN/OUT 조정",
        ["TrimSaveClipButton"] = "구간 저장",
        ["TrimExtractAudioButton"] = "오디오만",
        ["TrimExtractVideoButton"] = "비디오만",
        ["TooltipSaveTrim"] = "자른 구간을 파일로 저장 (탐색기 위치/이름 지정)",
        ["TooltipExtractAudio"] = "선택한 구간에서 오디오만 저장",
        ["TooltipExtractVideo"] = "선택한 구간에서 영상만 저장 (소리 없음)",

        ["PlaylistCurrentFolder"] = "현재 폴더",
        ["PlaylistSortTooltip"] = "재생목록 정렬",
        ["PlaylistSortNameAscending"] = "이름순 ↑",
        ["PlaylistSortNewestFirst"] = "최신순 ↓",
        ["PlaylistSortOldestFirst"] = "오래된순 ↑",
        ["RecentPlayback"] = "최근 재생",
        ["ItemSuffix"] = " 항목",
        ["OpenInExplorer"] = "탐색기에서 열기",
        ["CopyFilePath"] = "파일 경로 복사",
        ["Failure"] = "실패",
        ["RemoveThisItem"] = "이 항목 제거",
        ["ClearAll"] = "모두 비우기",

        ["SettingsTitle"] = "환경설정",
        ["SettingsHeader"] = "환경설정",
        ["SettingsDescription"] = "표시 언어, 스크린샷 저장 경로, Windows 연결 프로그램을 설정합니다.",
        ["LanguageHeader"] = "언어",
        ["LanguageDescription"] = "앱에서 사용할 언어를 선택하세요. 확인을 누르면 즉시 적용됩니다.",
        ["LanguageLabel"] = "표시 언어",
        ["ScreenshotFolderHeader"] = "스크린샷 저장 폴더",
        ["ScreenshotFolderDescription"] = "Ctrl+S 또는 카메라 버튼으로 저장한 PNG가 들어갈 폴더. 비워두면 기본값 (사용자\\사진\\Deno Video Player\\) 사용.",
        ["FileAssociationHeader"] = "연결 프로그램",
        ["FileAssociationDescription"] = "기본값은 동영상 및 오디오입니다. 확인을 누르면 선택한 확장자를 Windows '연결 프로그램' 및 '기본 앱' 목록에 등록하고 창을 닫습니다. 더블클릭 기본 앱을 지정하려면 아래 버튼으로 Windows 설정을 연 뒤 직접 선택해 주세요.",
        ["RegisterFileTypes"] = "선택한 확장자 등록",
        ["OpenDefaultAppsSettings"] = "Windows 기본 앱 설정 열기",
        ["Browse"] = "찾아보기...",
        ["Default"] = "기본값",
        ["Cancel"] = "취소",
        ["Confirm"] = "확인",
        ["Video"] = "동영상",
        ["Audio"] = "오디오",
        ["Image"] = "이미지",

        ["UpdateAvailable"] = "새 버전 {0} — 클릭해서 업데이트",
        ["UpdateReady"] = "새 버전 {0} 준비됨 — 클릭해서 재시작",
        ["UpdatePortableAvailable"] = "새 버전 {0} — 클릭해서 다운로드 페이지 열기",
        ["UpdateApplyFailed"] = "업데이트 적용에 실패했습니다",
        ["UpdateChecking"] = "업데이트 확인 중",
        ["UpdatePromptTitle"] = "새 버전이 있습니다",
        ["UpdatePromptAvailableMessage"] = "Deno Video Player {0} 업데이트가 있습니다.\n지금 업데이트하고 앱을 다시 시작할까요?",
        ["UpdatePromptReadyMessage"] = "Deno Video Player {0} 업데이트가 준비되었습니다.\n지금 적용하면 앱이 재시작됩니다.",
        ["UpdatePromptPortableMessage"] = "Deno Video Player {0} 업데이트가 있습니다.\n다운로드 페이지를 열까요?",
        ["UpdatePromptUpdateButton"] = "업데이트",
        ["UpdatePromptDownloadButton"] = "다운로드 열기",
        ["UpdatePromptCancelButton"] = "취소",
        ["RepeatTooltipNone"] = "반복 끔 (클릭: 전체 반복)",
        ["RepeatTooltipAll"] = "전체 반복 (클릭: 한 곡 반복)",
        ["RepeatTooltipOne"] = "한 곡 반복 (클릭: 끔)",
        ["ShuffleOn"] = "셔플 켜짐 (클릭: 끔)",
        ["ShuffleOff"] = "셔플 꺼짐 (클릭: 랜덤 재생)",
        ["NoSubtitleForMedia"] = "자막은 영상에서만 동작합니다",
        ["SubtitleTrackNext"] = "자막 트랙 ▶",
        ["SubtitleVisibilityToggle"] = "자막 표시 토글",
        ["NoPlayingMedia"] = "재생 중인 미디어가 없습니다",
        ["AudioTrackNext"] = "오디오 트랙 ▶",
        ["VideoZoomChanged"] = "확대 {0}",
        ["ImageCannotTrim"] = "이미지는 자르기 불가",
        ["TrimPointsCleared"] = "자르기 지점 초기화",
        ["TrimModeEntered"] = "편집 모드 — 양쪽 핸들 드래그로 IN/OUT 조정 → 저장 버튼",
        ["TrimModeExited"] = "편집 모드 종료",
        ["TrimModeCanceled"] = "편집 모드 취소",
        ["MpvIpcFailed"] = "mpv IPC 연결 실패",
        ["TrimNeedInOut"] = "IN/OUT 지점을 먼저 잡으세요",
        ["TrimInputMissing"] = "원본 파일을 찾을 수 없습니다: {0}",
        ["TrimInvalidRange"] = "OUT 지점이 IN 지점보다 뒤에 있어야 합니다.",
        ["TrimUnsupportedOutputMode"] = "지원하지 않는 출력 방식입니다.",
        ["TrimInvalidOutputPath"] = "출력 경로가 올바르지 않습니다: {0}",
        ["TrimSameInputOutputPath"] = "원본 파일과 같은 경로에는 저장할 수 없습니다.",
        ["TrimOutputDirectoryMissing"] = "출력 폴더를 찾을 수 없습니다.",
        ["TrimOutputExtensionMissing"] = "출력 파일 확장자가 필요합니다.",
        ["FfmpegProcessStartFailed"] = "FFmpeg 프로세스를 시작하지 못했습니다.",
        ["TrimOperationCanceled"] = "작업이 취소되었습니다.",
        ["FfmpegExitFailed"] = "FFmpeg가 종료 코드 {0}(으)로 실패했습니다.\n{1}",
        ["TrimOutputNotCreated"] = "출력 파일이 생성되지 않았습니다.",
        ["FfmpegPreparing"] = "처음 내보낼 때 필요한 FFmpeg를 준비하고 있습니다. 다운로드 크기가 클 수 있습니다.",
        ["FfmpegDownloading"] = "FFmpeg를 다운로드하고 있습니다. 잠시만 기다려 주세요.",
        ["FfmpegInstalling"] = "FFmpeg 압축을 풀고 있습니다.",
        ["FfmpegReady"] = "FFmpeg 준비가 끝났습니다.",
        ["FfmpegPrepareFailed"] = "FFmpeg를 준비하지 못했습니다: {0}",
        ["FfmpegExecutableMissing"] = "FFmpeg를 찾을 수 없습니다. 내보내기를 다시 시도해 자동 준비를 실행하세요. 계속 실패하면 도움말(F1)의 문제 해결을 확인하세요.",
        ["TrimSaveDialogTitle"] = "자르기 — 저장 위치/이름 지정",
        ["ExtractAudioSaveDialogTitle"] = "오디오만 추출 — 저장 위치/이름 지정",
        ["ExtractVideoSaveDialogTitle"] = "비디오만 추출 — 저장 위치/이름 지정",
        ["SameFormatFilter"] = "같은 형식 (*{0})|*{0}|모든 파일|*.*",
        ["AudioOutputFilter"] = "오디오 파일 (*{0})|*{0}|모든 파일|*.*",
        ["TrimInProgress"] = "자르기 진행 중...",
        ["ExtractAudioInProgress"] = "오디오 추출 중...",
        ["ExtractVideoInProgress"] = "비디오 추출 중...",
        ["TrimSaved"] = "저장됨: {0}",
        ["ExtractAudioSaved"] = "오디오 저장됨: {0}",
        ["ExtractVideoSaved"] = "비디오 저장됨: {0}",
        ["TrimFailed"] = "자르기 실패: {0}",
        ["ExtractAudioFailed"] = "오디오 추출 실패: {0}",
        ["ExtractVideoFailed"] = "비디오 추출 실패: {0}",
        ["VideoOnlyNeedsVideo"] = "비디오만 추출은 동영상에서만 가능합니다",
        ["OpenMediaDialogTitle"] = "미디어 파일 열기",
        ["OpenMediaFolderDialogTitle"] = "미디어 폴더 열기 (첫 파일부터 재생)",
        ["NoPlayableMediaInFolder"] = "이 폴더에 재생 가능한 미디어가 없습니다",
        ["OpenFolderFailed"] = "폴더 열기 실패: {0}",
        ["AllSupportedMediaFilter"] = "모든 지원 미디어|{0}|모든 파일|*.*",
        ["FileNotFound"] = "파일을 찾을 수 없습니다: {0}",
        ["UnsupportedFormat"] = "지원하지 않는 형식: {0}",
        ["MpvDisconnectedRestart"] = "mpv 재생 엔진 연결이 끊겼습니다. 재생 엔진을 다시 시도해주세요. 계속되면 앱을 다시 시작해주세요.",
        ["LoadingStatus"] = "로딩 중...",
        ["NoScreenshotWithoutMedia"] = "재생 중인 미디어가 없습니다",
        ["MpvDisconnectedToast"] = "mpv 연결이 끊겼습니다 — 앱 재시작 필요",
        ["AudioCannotScreenshot"] = "오디오 파일은 스크린샷할 수 없습니다",
        ["ScreenshotSaved"] = "스크린샷 저장 → {0}",
        ["ScreenshotNoResponse"] = "스크린샷 실패 — mpv 응답 없음",
        ["ScreenshotFailed"] = "스크린샷 실패: {0}",
        ["PlaybackFailedShort"] = "재생 실패",
        ["CannotPlayThisFile"] = "이 파일을 재생할 수 없습니다.",
        ["NoVideoForSubtitle"] = "자막을 추가할 영상이 없습니다 — 먼저 영상을 여세요",
        ["SubtitleOnlyVideo"] = "자막은 영상 파일에만 추가할 수 있습니다",
        ["SubtitlesAdded"] = "자막 {0}개 추가됨",
        ["FirstRunPreparing"] = "첫 실행을 준비하고 있어요...\n미디어 재생 엔진(mpv)을 다운로드 중입니다. 잠시만 기다려 주세요.",
        ["FirstRunPreparingTitle"] = "재생 엔진 준비 중",
        ["FirstRunPreparingHint"] = "처음 한 번만 진행됩니다. 인터넷 상태에 따라 잠시 걸릴 수 있어요.",
        ["FirstRunStageChecking"] = "최신 버전 확인 중...",
        ["FirstRunStageDownloading"] = "재생 엔진 다운로드 중...",
        ["FirstRunStageInstalling"] = "엔진 설치 중...",
        ["FirstRunStageReady"] = "재생 엔진 준비 완료. 플레이어를 시작하는 중...",
        ["FirstRunStageStarting"] = "플레이어를 시작하는 중...",
        ["FirstRunPrepareFailed"] = "재생 엔진을 준비하지 못했습니다.\n인터넷 연결을 확인한 뒤 ‘재생 엔진 다시 시도’를 눌러 주세요. 문제가 계속되면 앱을 다시 실행하거나 GitHub Releases에서 포터블 압축본을 새로 받아 보세요.\n\n{0}",
        ["VideoHostFailed"] = "내부 오류: 비디오 호스트 hwnd가 생성되지 않았습니다.",
        ["MpvStartFailed"] = "mpv 시작 실패: {0}",
        ["MpvExecutableMissing"] = "재생 엔진을 찾을 수 없습니다.\n경로: {0}\nF1 도움말의 문제 해결을 확인해 주세요.",
        ["MpvProcessStartFailed"] = "재생 엔진 프로세스를 시작하지 못했습니다.",
        ["MpvProcessRepeatedExit"] = "mpv 프로세스가 반복 종료되었습니다. 앱을 다시 시작해주세요.",
        ["MpvRestartFailed"] = "mpv 재시작 실패: {0}",
        ["RuntimeScriptMissing"] = "필요한 {0} 준비 스크립트를 찾을 수 없습니다:\n{1}",
        ["RuntimePrepareProcessStartFailed"] = "{0} 준비 프로세스를 시작하지 못했습니다.",
        ["RuntimeExecutableValidationFailed"] = "{0} 실행 파일 검증에 실패했습니다. 다시 시도해 주세요.",
        ["RuntimePrepareDetailFailed"] = "{0} 준비에 실패했습니다.\n{1}",
        ["RuntimePrepareCanceled"] = "{0} 준비가 취소되었습니다.",
        ["RuntimePrepareTimeout"] = "{0} 다운로드 시간이 초과되었습니다. 인터넷 연결을 확인한 뒤 다시 시도하세요.",
        ["SettingsOpenFailed"] = "환경설정 창을 열 수 없습니다:\n{0}",
        ["UnexpectedError"] = "예기치 못한 오류:\n{0}",
        ["UiError"] = "UI 예외:\n{0}",
        ["SettingsSaveError"] = "설정을 저장하지 못했습니다:\n{0}",
        ["SettingsSaveFailedToast"] = "설정을 저장하지 못했습니다. 저장 공간과 폴더 권한을 확인하세요.",
        ["SettingsApplyError"] = "설정을 적용하지 못했습니다:\n{0}",
        ["PickScreenshotFolderTitle"] = "스크린샷 저장 폴더 선택",
        ["PickFolderFailed"] = "폴더 선택 실패: {0}",
        ["SettingsRegisterComplete"] = "등록 완료 ({0}개 확장자).\n\n탐색기 우클릭 → '연결 프로그램' 메뉴에 Deno Video Player가 나오고,\nWindows '기본 앱' 화면에도 'Deno Video Player' 항목이 추가됐습니다.\n\n지금 그 화면을 열까요? — Deno Video Player 항목 클릭 후 각 확장자를\nDeno Video Player로 지정하면 더블클릭 시 우리 앱이 열립니다.\n\n(Windows 정책상 기본 앱 변경은 사용자가 직접 눌러야 적용됩니다)",
        ["SettingsRegisterError"] = "등록 중 오류:\n{0}",

        ["HelpTitle"] = "도움말 · Deno Video Player",
        ["HelpHeader"] = "빠른 사용법",
        ["HelpDescription"] = "파일을 열고 재생을 확인한 뒤 필요한 기능만 꺼내 쓰는 방법을 한곳에 모았습니다. 언제든 F1로 다시 열 수 있습니다.",
        ["HelpQuickStartHeader"] = "처음 30초",
        ["HelpQuickOpenTitle"] = "파일 또는 폴더 열기",
        ["HelpQuickOpenBody"] = "창에 파일을 끌어다 놓거나 Ctrl+O, 파일 열기·폴더 열기 버튼을 사용하세요. 폴더를 열면 첫 미디어와 같은 종류의 파일이 재생목록에 들어옵니다. 빈 화면 더블클릭은 창 크기를 전환합니다.",
        ["HelpQuickPlayTitle"] = "재생하고 필요한 부분 확인하기",
        ["HelpQuickPlayBody"] = "Space로 재생·일시정지하고, ←/→로 5초씩 이동합니다. Space를 길게 누르는 동안에는 2배속으로 확인할 수 있습니다.",
        ["HelpQuickPanelsTitle"] = "목록은 손잡이 또는 버튼으로 열기",
        ["HelpQuickPanelsBody"] = "좌우 가장자리 중앙의 얇은 손잡이에 마우스를 올리면 왼쪽은 최근 파일, 오른쪽은 재생목록이 열립니다. 손잡이와 패널을 벗어나면 닫힙니다. 계속 열어두려면 상단 버튼이나 Ctrl+H(최근), P / Ctrl+L(목록)을 쓰세요. 목록 상단에서 이름순·최신순·오래된순 정렬을 선택할 수 있습니다.",
        ["HelpButtonsHeader"] = "화면 버튼과 패널",
        ["HelpButtonsIntro"] = "상단은 파일과 작업 도구, 하단은 재생 조작입니다. 아이콘 위에 마우스를 올리면 기능과 대표 단축키가 표시됩니다.",
        ["HelpButtonsLibraryLabel"] = "최근 · 목록 · 폴더 · 파일 · ? · 설정",
        ["HelpButtonsLibraryBody"] = "최근 파일이나 현재 폴더 목록을 열고, 폴더나 파일을 선택하고, 이 도움말과 환경설정을 엽니다. 환경설정에서는 언어·스크린샷 폴더·Windows 연결 프로그램을 바꿀 수 있습니다.",
        ["HelpButtonsToolsLabel"] = "핀 · 카메라 · 가위",
        ["HelpButtonsToolsBody"] = "창을 항상 위에 두거나 현재 영상·이미지를 캡처하고, 재인코딩 없는 구간 저장 모드로 들어갑니다.",
        ["HelpButtonsPlaybackLabel"] = "하단 조작부",
        ["HelpButtonsPlaybackBody"] = "이전/다음, 재생, 반복, 셔플, 음량, 배속, 전체화면을 조작합니다. 반복 버튼은 반복 없음·전체 반복·한 항목 반복 중 하나를 선택합니다. 전체화면에서는 추가 버튼으로 조작부까지 숨겨 영상만 볼 수 있습니다.",
        ["HelpShortcutsHeader"] = "자주 쓰는 키와 마우스",
        ["HelpShortcutPlay"] = "짧게 누르면 재생/일시정지, 길게 누르는 동안 2배속",
        ["HelpShortcutSeek"] = "5초 이동 · Shift를 함께 누르면 30초 이동",
        ["HelpShortcutVolume"] = "마우스 휠 또는 ↑/↓로 음량 조절 · M은 음소거/해제",
        ["HelpShortcutFiles"] = "같은 종류의 이전/다음 파일 · Ctrl + ←/→도 동일",
        ["HelpShortcutFullscreen"] = "일반 창 ↔ 전체화면 전환(Alt + Enter도 동일). 화면·제목줄 더블클릭과 우측 상·하단 크기 버튼도 같습니다. 최대화 상태에서는 원래 창 크기로 돌아옵니다. Esc로 종료하며, 구간 편집 중 첫 Esc는 편집을 취소합니다.",
        ["HelpShortcutZoom"] = "영상 확대/축소 · 확대한 영상을 가운데 버튼으로 드래그",
        ["HelpShortcutPlaylist"] = "최근 파일 또는 현재 폴더 재생목록 열기/닫기",
        ["HelpShortcutCapturePin"] = "스크린샷 저장 · 창을 항상 위에 두기",
        ["HelpShortcutTracks"] = "다음 자막 · 자막 표시/숨기기 · 다음 오디오 트랙",
        ["HelpShortcutSpeedFrames"] = "한 프레임 이동 · Shift와 함께 누르면 배속 ±0.25",
        ["HelpTrimHeader"] = "구간 저장",
        ["HelpTrimBody"] = "상단 가위 버튼을 누르고 양쪽 핸들로 IN/OUT을 조정한 뒤 구간 저장, 오디오만, 비디오만 중에서 선택하세요. 키보드로는 시작점 I, 끝점 O, 저장 Ctrl+E이며 키보드 X는 지점을 초기화합니다. 상단의 편집 취소 X 또는 Esc로 저장하지 않고 나갈 수 있습니다.",
        ["HelpTrimNote"] = "첫 내보내기에는 FFmpeg 준비와 큰 다운로드가 필요할 수 있습니다. 재인코딩하지 않아 빠르고 화질 손실이 없지만, 저장 경계는 키프레임 근처로 조금 달라질 수 있습니다.",
        ["HelpTroubleshootingHeader"] = "문제 해결",
        ["HelpTroubleshootingEngine"] = "재생 엔진 준비에 실패하면 실패 화면의 ‘재생 엔진 다시 시도’를 누르세요. 계속 실패하면 인터넷 연결을 확인하고 앱을 다시 실행하거나 공식 설치 파일·포터블 압축본을 새로 받아 보세요.",
        ["HelpTroubleshootingPlayback"] = "특정 파일만 열리지 않으면 손상되었거나 지원되지 않는 형식일 수 있습니다. 다른 파일을 먼저 열어 재생 엔진이 정상인지 확인하세요. 자막은 영상이 열린 상태에서 창에 끌어다 놓을 수 있습니다.",
        ["HelpTroubleshootingExport"] = "구간·오디오·비디오 저장이 처음 실패하면 인터넷 연결을 확인하고 다시 시도하세요. 앱이 FFmpeg를 자동으로 준비합니다. 준비가 반복해서 실패하면 앱을 다시 실행한 뒤 내보내기를 다시 시도하세요.",
        ["HelpTroubleshootingRecent"] = "연결이 끊긴 외장·네트워크 파일은 최근 목록에 남습니다. 드라이브를 다시 연결해 열거나, 필요 없으면 최근 항목을 우클릭해 ‘목록에서 제거’를 선택하세요.",
        ["CloseHelp"] = "닫기",
    };

    private static readonly Dictionary<string, string> EnglishStrings = new()
    {
        ["AppName"] = "Deno Video Player",
        ["TooltipRecent"] = "Recent files (Ctrl+H) · left-center handle",
        ["TooltipPlaylist"] = "Playlist (P / Ctrl+L) · right-center handle",
        ["TooltipAlwaysOnTop"] = "Always on top (Ctrl+T)",
        ["TooltipScreenshot"] = "Screenshot (Ctrl+S)",
        ["TooltipTrimStart"] = "Start trim editing",
        ["TooltipTrimExit"] = "Exit trim editing without saving",
        ["TooltipTrimCancel"] = "Cancel trim editing",
        ["TooltipOpenFolder"] = "Open folder",
        ["TooltipOpenFile"] = "Open file (Ctrl+O)",
        ["TooltipHelp"] = "Help and shortcuts (F1)",
        ["TooltipSettings"] = "Settings — file associations",
        ["TooltipMinimize"] = "Minimize",
        ["TooltipMaxRestore"] = "Fullscreen / restore window (F)",
        ["TooltipClose"] = "Close",
        ["AudioPlaying"] = "Playing audio",
        ["HeroBrand"] = "DENO VIDEO PLAYER",
        ["DropHeadline"] = "Drop media here",
        ["DropSubline"] = "Or press Ctrl+O / use the buttons below",
        ["OpenFile"] = "Open file",
        ["OpenFolder"] = "Open folder",
        ["HelpFirstUse"] = "New here? Open the quick guide (F1)",
        ["SupportedFormats"] = ".mp4 .mkv .mov .webm  ·  .mp3 .flac .wav  ·  .png .jpg .gif",
        ["PlaybackFailed"] = "Cannot play this file",
        ["PlaybackEngineFailed"] = "The playback engine is unavailable",
        ["OpenOtherFile"] = "Open another file",
        ["NextFile"] = "Next file",
        ["RetryPlaybackEngine"] = "Retry playback engine",
        ["Troubleshooting"] = "Troubleshooting",
        ["Loading"] = "Loading",
        ["TrimInPoint"] = "IN point",
        ["TrimOutPoint"] = "OUT point",
        ["TooltipPrev"] = "Previous file (PageUp / Ctrl+Left)",
        ["TooltipPlayPause"] = "Play / pause (Space)",
        ["TooltipNext"] = "Next file (PageDown / Ctrl+Right)",
        ["TooltipRepeatNone"] = "No repeat (stop after one pass)",
        ["TooltipRepeatAll"] = "Repeat all (wrap to first file)",
        ["TooltipRepeatOne"] = "Repeat one (keep playing current file)",
        ["TooltipMute"] = "Mute (M)",
        ["TooltipSpeed"] = "Speed — click: presets, wheel: ±0.25, Shift + . / Shift + ,",
        ["SpeedDefault"] = "1.0x — Default",
        ["TooltipFullscreen"] = "Fullscreen / restore window (F)",
        ["TooltipImmersiveFullscreen"] = "Hide controls (keep window size)",
        ["TrimEditingPrefix"] = "Editing — ",
        ["TrimEditingSuffix"] = "  ·  Drag both handles to adjust IN/OUT",
        ["TrimSaveClipButton"] = "Save clip",
        ["TrimExtractAudioButton"] = "Audio only",
        ["TrimExtractVideoButton"] = "Video only",
        ["TooltipSaveTrim"] = "Save the selected range as a file",
        ["TooltipExtractAudio"] = "Save only the audio from the selected range",
        ["TooltipExtractVideo"] = "Save only the video from the selected range (no audio)",

        ["PlaylistCurrentFolder"] = "Current folder",
        ["PlaylistSortTooltip"] = "Sort playlist",
        ["PlaylistSortNameAscending"] = "Name ↑",
        ["PlaylistSortNewestFirst"] = "Newest ↓",
        ["PlaylistSortOldestFirst"] = "Oldest ↑",
        ["RecentPlayback"] = "Recent files",
        ["ItemSuffix"] = " items",
        ["OpenInExplorer"] = "Reveal in File Explorer",
        ["CopyFilePath"] = "Copy file path",
        ["Failure"] = "Failed",
        ["RemoveThisItem"] = "Remove this item",
        ["ClearAll"] = "Clear all",

        ["SettingsTitle"] = "Settings",
        ["SettingsHeader"] = "Settings",
        ["SettingsDescription"] = "Manage display language, screenshot folder, and Windows file associations.",
        ["LanguageHeader"] = "Language",
        ["LanguageDescription"] = "Choose the app's display language. Changes apply after clicking OK.",
        ["LanguageLabel"] = "Display language",
        ["ScreenshotFolderHeader"] = "Screenshot folder",
        ["ScreenshotFolderDescription"] = "PNG screenshots from Ctrl+S or the camera button are saved here. Leave blank to use Pictures\\Deno Video Player\\.",
        ["FileAssociationHeader"] = "File associations",
        ["FileAssociationDescription"] = "Video and audio are selected by default. Clicking OK registers the selected extensions in Windows 'Open with' and Default Apps, then closes this window. Use the button below to open Windows Settings and choose the final double-click defaults.",
        ["RegisterFileTypes"] = "Register extensions",
        ["OpenDefaultAppsSettings"] = "Open Windows Default Apps",
        ["Browse"] = "Browse...",
        ["Default"] = "Default",
        ["Cancel"] = "Cancel",
        ["Confirm"] = "OK",
        ["Video"] = "Video",
        ["Audio"] = "Audio",
        ["Image"] = "Image",

        ["UpdateAvailable"] = "New version {0} — click to update",
        ["UpdateReady"] = "New version {0} is ready — click to restart",
        ["UpdatePortableAvailable"] = "New version {0} — click to open downloads",
        ["UpdateApplyFailed"] = "Could not apply the update",
        ["UpdateChecking"] = "Checking for updates",
        ["UpdatePromptTitle"] = "Update Available",
        ["UpdatePromptAvailableMessage"] = "Deno Video Player {0} is available.\nUpdate and restart the app now?",
        ["UpdatePromptReadyMessage"] = "Deno Video Player {0} is ready.\nApply it now? The app will restart.",
        ["UpdatePromptPortableMessage"] = "Deno Video Player {0} is available.\nOpen the download page?",
        ["UpdatePromptUpdateButton"] = "Update",
        ["UpdatePromptDownloadButton"] = "Open Downloads",
        ["UpdatePromptCancelButton"] = "Cancel",
        ["RepeatTooltipNone"] = "Repeat off (click: repeat all)",
        ["RepeatTooltipAll"] = "Repeat all (click: repeat one)",
        ["RepeatTooltipOne"] = "Repeat one (click: off)",
        ["ShuffleOn"] = "Shuffle on (click: off)",
        ["ShuffleOff"] = "Shuffle off (click: random playback)",
        ["NoSubtitleForMedia"] = "Subtitles only work with video",
        ["SubtitleTrackNext"] = "Subtitle track ▶",
        ["SubtitleVisibilityToggle"] = "Subtitle visibility toggled",
        ["NoPlayingMedia"] = "No media is playing",
        ["AudioTrackNext"] = "Audio track ▶",
        ["VideoZoomChanged"] = "Zoom {0}",
        ["ImageCannotTrim"] = "Images cannot be trimmed",
        ["TrimPointsCleared"] = "Trim points cleared",
        ["TrimModeEntered"] = "Trim editing — drag both handles to adjust IN/OUT → Save",
        ["TrimModeExited"] = "Trim editing closed",
        ["TrimModeCanceled"] = "Trim editing canceled",
        ["MpvIpcFailed"] = "mpv IPC connection failed",
        ["TrimNeedInOut"] = "Set IN and OUT points first",
        ["TrimInputMissing"] = "The source file could not be found: {0}",
        ["TrimInvalidRange"] = "The OUT point must be after the IN point.",
        ["TrimUnsupportedOutputMode"] = "This output mode is not supported.",
        ["TrimInvalidOutputPath"] = "The output path is invalid: {0}",
        ["TrimSameInputOutputPath"] = "The output cannot use the same path as the source file.",
        ["TrimOutputDirectoryMissing"] = "The output folder could not be found.",
        ["TrimOutputExtensionMissing"] = "The output filename needs an extension.",
        ["FfmpegProcessStartFailed"] = "Could not start the FFmpeg process.",
        ["TrimOperationCanceled"] = "The operation was canceled.",
        ["FfmpegExitFailed"] = "FFmpeg failed with exit code {0}.\n{1}",
        ["TrimOutputNotCreated"] = "The output file was not created.",
        ["FfmpegPreparing"] = "Preparing FFmpeg for the first export. The download can be large.",
        ["FfmpegDownloading"] = "Downloading FFmpeg. Please wait.",
        ["FfmpegInstalling"] = "Extracting FFmpeg.",
        ["FfmpegReady"] = "FFmpeg is ready.",
        ["FfmpegPrepareFailed"] = "Could not prepare FFmpeg: {0}",
        ["FfmpegExecutableMissing"] = "FFmpeg could not be found. Retry the export to run automatic setup. If it still fails, open Help (F1) and see Troubleshooting.",
        ["TrimSaveDialogTitle"] = "Trim — choose save location and name",
        ["ExtractAudioSaveDialogTitle"] = "Audio only — choose save location and name",
        ["ExtractVideoSaveDialogTitle"] = "Video only — choose save location and name",
        ["SameFormatFilter"] = "Same format (*{0})|*{0}|All files|*.*",
        ["AudioOutputFilter"] = "Audio file (*{0})|*{0}|All files|*.*",
        ["TrimInProgress"] = "Trimming...",
        ["ExtractAudioInProgress"] = "Extracting audio...",
        ["ExtractVideoInProgress"] = "Extracting video...",
        ["TrimSaved"] = "Saved: {0}",
        ["ExtractAudioSaved"] = "Audio saved: {0}",
        ["ExtractVideoSaved"] = "Video saved: {0}",
        ["TrimFailed"] = "Trim failed: {0}",
        ["ExtractAudioFailed"] = "Audio extract failed: {0}",
        ["ExtractVideoFailed"] = "Video extract failed: {0}",
        ["VideoOnlyNeedsVideo"] = "Video-only export requires a video file",
        ["OpenMediaDialogTitle"] = "Open media file",
        ["OpenMediaFolderDialogTitle"] = "Open media folder (play from first file)",
        ["NoPlayableMediaInFolder"] = "No playable media found in this folder",
        ["OpenFolderFailed"] = "Open folder failed: {0}",
        ["AllSupportedMediaFilter"] = "All supported media|{0}|All files|*.*",
        ["FileNotFound"] = "File not found: {0}",
        ["UnsupportedFormat"] = "Unsupported format: {0}",
        ["MpvDisconnectedRestart"] = "The mpv playback engine disconnected. Retry the playback engine. If the problem continues, restart the app.",
        ["LoadingStatus"] = "Loading...",
        ["NoScreenshotWithoutMedia"] = "No media is playing",
        ["MpvDisconnectedToast"] = "mpv disconnected — restart required",
        ["AudioCannotScreenshot"] = "Audio files cannot be screenshotted",
        ["ScreenshotSaved"] = "Screenshot saved → {0}",
        ["ScreenshotNoResponse"] = "Screenshot failed — no mpv response",
        ["ScreenshotFailed"] = "Screenshot failed: {0}",
        ["PlaybackFailedShort"] = "Playback failed",
        ["CannotPlayThisFile"] = "This file cannot be played.",
        ["NoVideoForSubtitle"] = "Open a video before adding subtitles",
        ["SubtitleOnlyVideo"] = "Subtitles can only be added to video files",
        ["SubtitlesAdded"] = "{0} subtitle file(s) added",
        ["FirstRunPreparing"] = "Preparing for first launch...\nDownloading the mpv playback engine. Please wait a moment.",
        ["FirstRunPreparingTitle"] = "Preparing playback engine",
        ["FirstRunPreparingHint"] = "This is needed only once. It may take a moment depending on your connection.",
        ["FirstRunStageChecking"] = "Checking for updates...",
        ["FirstRunStageDownloading"] = "Downloading playback engine...",
        ["FirstRunStageInstalling"] = "Installing engine...",
        ["FirstRunStageReady"] = "Playback engine is ready. Starting the player...",
        ["FirstRunStageStarting"] = "Starting the player...",
        ["FirstRunPrepareFailed"] = "Failed to prepare the playback engine.\nCheck your internet connection, then choose Retry playback engine. If the issue persists, restart the app or download a fresh portable archive from GitHub Releases.\n\n{0}",
        ["VideoHostFailed"] = "Internal error: the video host window was not created.",
        ["MpvStartFailed"] = "mpv failed to start: {0}",
        ["MpvExecutableMissing"] = "The playback engine could not be found.\nPath: {0}\nOpen Help (F1) and see Troubleshooting.",
        ["MpvProcessStartFailed"] = "The playback engine process could not be started.",
        ["MpvProcessRepeatedExit"] = "mpv exited repeatedly. Please restart the app.",
        ["MpvRestartFailed"] = "mpv restart failed: {0}",
        ["RuntimeScriptMissing"] = "The required {0} setup script could not be found:\n{1}",
        ["RuntimePrepareProcessStartFailed"] = "Could not start the {0} setup process.",
        ["RuntimeExecutableValidationFailed"] = "The prepared {0} executable failed validation. Please retry.",
        ["RuntimePrepareDetailFailed"] = "{0} setup failed.\n{1}",
        ["RuntimePrepareCanceled"] = "{0} setup was canceled.",
        ["RuntimePrepareTimeout"] = "The {0} download timed out. Check your connection and retry.",
        ["SettingsOpenFailed"] = "Could not open Settings:\n{0}",
        ["UnexpectedError"] = "Unexpected error:\n{0}",
        ["UiError"] = "UI error:\n{0}",
        ["SettingsSaveError"] = "Could not save settings:\n{0}",
        ["SettingsSaveFailedToast"] = "Could not save settings. Check free space and folder permissions.",
        ["SettingsApplyError"] = "Could not apply settings:\n{0}",
        ["PickScreenshotFolderTitle"] = "Choose screenshot folder",
        ["PickFolderFailed"] = "Folder selection failed: {0}",
        ["SettingsRegisterComplete"] = "Registration complete ({0} extensions).\n\nDeno Video Player now appears in File Explorer's 'Open with' menu,\nand in Windows Default apps.\n\nOpen that Windows screen now? Select Deno Video Player there for each extension you want to open by double-clicking.\n\n(Windows requires the user to confirm default app changes manually.)",
        ["SettingsRegisterError"] = "Registration error:\n{0}",

        ["HelpTitle"] = "Help · Deno Video Player",
        ["HelpHeader"] = "Quick guide",
        ["HelpDescription"] = "A practical guide to opening a file, checking playback, and using only the tools you need. Press F1 to return here at any time.",
        ["HelpQuickStartHeader"] = "The first 30 seconds",
        ["HelpQuickOpenTitle"] = "Open a file or folder",
        ["HelpQuickOpenBody"] = "Drop a file onto the window, press Ctrl+O, or use Open file / Open folder. Opening a folder adds media of the same kind as the first item to the playlist. Double-clicking the empty viewing area toggles the window size.",
        ["HelpQuickPlayTitle"] = "Play and review",
        ["HelpQuickPlayBody"] = "Press Space to play or pause and use ←/→ to seek by 5 seconds. Hold Space for temporary 2x playback.",
        ["HelpQuickPanelsTitle"] = "Open lists from handles or buttons",
        ["HelpQuickPanelsBody"] = "Hover the slim handle at the center of the left edge for Recent files, or the right edge for the playlist. Move away from both the handle and panel to close it. To keep a panel open, use its toolbar button, Ctrl+H (Recent), or P / Ctrl+L (playlist). Sort the playlist by natural name, newest first, or oldest first at the top.",
        ["HelpButtonsHeader"] = "Buttons and panels",
        ["HelpButtonsIntro"] = "The top bar contains file and task tools; the bottom bar controls playback. Hover an icon to see its action and primary shortcut.",
        ["HelpButtonsLibraryLabel"] = "Recent · list · folder · file · ? · settings",
        ["HelpButtonsLibraryBody"] = "Open recent files or the current-folder list, choose a folder or file, open this guide, or change settings. Settings manages language, screenshot location, and Windows file associations.",
        ["HelpButtonsToolsLabel"] = "Pin · camera · scissors",
        ["HelpButtonsToolsBody"] = "Keep the player above other windows, capture the current video or image, or enter the no-reencode clip export mode.",
        ["HelpButtonsPlaybackLabel"] = "Bottom controls",
        ["HelpButtonsPlaybackBody"] = "Control previous/next, playback, repeat, shuffle, volume, speed, and fullscreen. The repeat buttons select off, all, or the current item. In fullscreen, an extra button hides the controls for a video-only view.",
        ["HelpShortcutsHeader"] = "Useful keys and mouse actions",
        ["HelpShortcutPlay"] = "Tap to play/pause · hold for temporary 2x playback",
        ["HelpShortcutSeek"] = "Seek 5 seconds · hold Shift to seek 30 seconds",
        ["HelpShortcutVolume"] = "Use the mouse wheel or ↑/↓ to adjust volume · M toggles mute",
        ["HelpShortcutFiles"] = "Previous/next file of the same media kind · Ctrl + Left/Right does the same",
        ["HelpShortcutFullscreen"] = "Toggle windowed / fullscreen (Alt + Enter also works). Double-clicking the viewing area or title bar and the upper/lower-right size buttons do the same. A maximized window returns to its normal size. Esc exits; during trim editing, the first Esc cancels the edit.",
        ["HelpShortcutZoom"] = "Zoom video · middle-drag the zoomed image",
        ["HelpShortcutPlaylist"] = "Open or close Recent files or the current-folder playlist",
        ["HelpShortcutCapturePin"] = "Save a screenshot · keep the window always on top",
        ["HelpShortcutTracks"] = "Next subtitle · show/hide subtitles · next audio track",
        ["HelpShortcutSpeedFrames"] = "Step one frame · hold Shift to change speed by 0.25",
        ["HelpTrimHeader"] = "Save a range",
        ["HelpTrimBody"] = "Click the scissors, drag the IN/OUT handles, then choose Save clip, Audio only, or Video only. From the keyboard use I for IN, O for OUT, Ctrl+E to save, and keyboard X to clear the points. Use the top-bar cancel X or Esc to leave without saving.",
        ["HelpTrimNote"] = "The first export may need a large FFmpeg download. Stream copy is fast and does not re-encode, but the saved boundaries can move slightly to nearby keyframes.",
        ["HelpTroubleshootingHeader"] = "Troubleshooting",
        ["HelpTroubleshootingEngine"] = "If playback-engine setup fails, choose Retry playback engine on the failure screen. If it continues, check your connection, restart the app, or download a fresh official installer or portable archive.",
        ["HelpTroubleshootingPlayback"] = "If only one file fails, it may be damaged or unsupported. Open a different file to confirm the playback engine works. To add subtitles, first open a video and then drop the subtitle file onto the window.",
        ["HelpTroubleshootingExport"] = "If the first clip, audio, or video export fails, check your connection and retry. The app prepares FFmpeg automatically. If setup keeps failing, restart the app and retry the export.",
        ["HelpTroubleshootingRecent"] = "Files on a disconnected removable or network drive stay in Recent files. Reconnect the drive to open them, or right-click an entry and choose Remove from list when it is no longer needed.",
        ["CloseHelp"] = "Close",
    };
}
